# Generated by Django 3.2.6 on 2021-09-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='店舗名')),
                ('postcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='住所')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='E-mail')),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='FAX')),
                ('bank', models.CharField(blank=True, default='', max_length=20, verbose_name='銀行名')),
                ('bankbranch', models.CharField(blank=True, default='', max_length=20, verbose_name='支店名')),
                ('bankaccount', models.CharField(blank=True, default='', max_length=20, verbose_name='口座')),
                ('bankid', models.CharField(blank=True, default='', max_length=100, verbose_name='名義')),
                ('bankkana', models.CharField(blank=True, default='', max_length=100, verbose_name='フリガナ')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '51_店舗データ',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=20, verbose_name='姓')),
                ('firstname', models.CharField(default='', max_length=20, verbose_name='名')),
                ('lastnamekana', models.CharField(default='', max_length=20, verbose_name='姓（フリガナ）')),
                ('firstnamekana', models.CharField(default='', max_length=20, verbose_name='名（フリガナ）')),
                ('honorific', models.CharField(blank=True, default='様', max_length=10, verbose_name='敬称')),
                ('age', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], default='', max_length=1, verbose_name='性別')),
                ('birthday', models.CharField(blank=True, default='年月日', max_length=20, verbose_name='生年月日')),
                ('postcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, default='', max_length=100, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, verbose_name='住所2')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='E-mail')),
                ('tel1', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号1')),
                ('tel2', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号2')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='FAX')),
                ('moveInDate', models.DateField(blank=True, default='', verbose_name='入居日')),
                ('contractCategory', models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Buy', '購入'), ('Sell', '売却'), ('Other', 'その他')], default='', max_length=10, verbose_name='契約種別')),
                ('contractInfo', models.CharField(default='', max_length=20, verbose_name='契約情報')),
                ('remarks', models.TextField(blank=True, default='特記なし', verbose_name='特記事項')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '11_顧客データ',
            },
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyname', models.CharField(default='', max_length=100, verbose_name='物件名')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='住所')),
                ('room', models.CharField(blank=True, default='', max_length=10, verbose_name='部屋番号')),
                ('madori', models.CharField(blank=True, default='', max_length=10, verbose_name='間取り')),
                ('floor', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='階数')),
                ('contractCategory', models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Trade', '売買'), ('Other', 'その他')], default='', max_length=10, verbose_name='契約種別')),
                ('remarks', models.TextField(blank=True, default='特記なし', verbose_name='特記事項')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '12_物件データ',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(default='', max_length=20, verbose_name='姓')),
                ('firstname', models.CharField(default='', max_length=20, verbose_name='名')),
                ('lastnamekana', models.CharField(default='', max_length=20, verbose_name='姓（フリガナ）')),
                ('firstnamekana', models.CharField(default='', max_length=20, verbose_name='名（フリガナ）')),
                ('department', models.CharField(blank=True, default='', max_length=10, verbose_name='部署')),
                ('age', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], default='', max_length=1, verbose_name='性別')),
                ('birthday', models.CharField(blank=True, default='年月日', max_length=20, verbose_name='生年月日')),
                ('postcode', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, default='', max_length=100, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, verbose_name='住所2')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='E-mail')),
                ('tel1', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号1')),
                ('tel2', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号2')),
                ('fax', models.CharField(blank=True, default='', max_length=20, verbose_name='FAX')),
                ('remarks', models.TextField(blank=True, default='特記なし', verbose_name='特記事項')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '52_スタッフデータ',
            },
        ),
        migrations.CreateModel(
            name='ContModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='契約概要')),
                ('offerdate', models.DateField(blank=True, default='', verbose_name='申込日')),
                ('contractdate', models.DateField(blank=True, default='', verbose_name='契約開始日')),
                ('occupdate', models.DateField(blank=True, default='', verbose_name='入居日')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
                ('corp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='docs.corpmodel', verbose_name='担当店舗')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.customermodel', verbose_name='契約者')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.propertymodel', verbose_name='物件')),
                ('staff', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='docs.staffmodel', verbose_name='担当者')),
            ],
            options={
                'verbose_name_plural': '01_契約データ',
            },
        ),
    ]
