# Generated by Django 3.2.6 on 2021-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='category',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, max_length=3, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='contractCategory',
            field=models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Buy', '購入'), ('Sell', '売却')], max_length=10, null=True, verbose_name='契約種別'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='fax',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='ファックス番号'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], max_length=1, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='honorific',
            field=models.CharField(blank=True, choices=[('A', '様'), ('B', '御中')], default='様', max_length=10, null=True, verbose_name='敬称'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='moveInDate',
            field=models.DateField(blank=True, null=True, verbose_name='入居日'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='tel',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='update',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='firstname',
            field=models.CharField(default='', max_length=20, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='lastname',
            field=models.CharField(default='', max_length=20, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='postdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='特記事項'),
        ),
    ]
