# Generated by Django 3.2.6 on 2021-09-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='limit',
            field=models.DateField(auto_now=True, null=True, verbose_name='差引残金期日'),
        ),
    ]
