# Generated by Django 3.2.6 on 2021-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_contractmodel_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='limit',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='差引残金期日'),
        ),
    ]
