# Generated by Django 3.2.6 on 2021-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210910_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='fax',
            field=models.IntegerField(blank=True, null=True, verbose_name='ファックス番号'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tel',
            field=models.IntegerField(blank=True, null=True, verbose_name='電話番号'),
        ),
    ]
