# Generated by Django 3.2.6 on 2021-09-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210912_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contmodel',
            name='contractdate',
            field=models.DateField(blank=True, default='', null=True, verbose_name='契約開始日'),
        ),
        migrations.AlterField(
            model_name='contmodel',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.corpmodel', verbose_name='担当店舗'),
        ),
        migrations.AlterField(
            model_name='contmodel',
            name='occupdate',
            field=models.DateField(blank=True, default='', null=True, verbose_name='入居日'),
        ),
        migrations.AlterField(
            model_name='contmodel',
            name='staff',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.staffmodel', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='銀行名'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='bankaccount',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='口座'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='bankbranch',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='支店名'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='bankid',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='名義'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='bankkana',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='フリガナ'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='corpmodel',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default='', null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='birthday',
            field=models.CharField(blank=True, default='年月日', max_length=20, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='contractCategory',
            field=models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Buy', '購入'), ('Sell', '売却'), ('Other', 'その他')], default='', max_length=10, null=True, verbose_name='契約種別'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='contractInfo',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='契約情報'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性'), ('3', 'その他')], default='', max_length=1, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='honorific',
            field=models.CharField(blank=True, default='様', max_length=10, null=True, verbose_name='敬称'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='moveInDate',
            field=models.DateField(blank=True, default='', null=True, verbose_name='入居日'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='remarks',
            field=models.TextField(blank=True, default='特記なし', null=True, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tel1',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='電話番号1'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tel2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='電話番号2'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='contractCategory',
            field=models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Trade', '売買'), ('Other', 'その他')], default='', max_length=10, null=True, verbose_name='契約種別'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, default='', null=True, verbose_name='階数'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='madori',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='間取り'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='remarks',
            field=models.TextField(blank=True, default='特記なし', null=True, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='room',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='部屋番号'),
        ),
    ]
