# Generated by Django 3.2.6 on 2021-09-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_contractmodel_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='month1',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='当月'),
        ),
    ]
