# Generated by Django 3.2.6 on 2021-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210910_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='postcode',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='honorific',
            field=models.CharField(blank=True, default='様', max_length=10, null=True, verbose_name='敬称'),
        ),
    ]
