# Generated by Django 3.2.6 on 2021-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210912_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContModel',
            new_name='ContractModel',
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='生年月日'),
        ),
    ]
