# Generated by Django 3.2.6 on 2021-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20210910_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birthday',
            field=models.CharField(blank=True, default='年月日', max_length=20, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ファックス番号'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='remarks',
            field=models.TextField(blank=True, default='特記なし', null=True, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
