# Generated by Django 3.2.6 on 2021-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_contractmodel_month1'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month1b', models.IntegerField(default=9)),
                ('month2b', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month1',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='当月'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month2',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True, verbose_name='翌月'),
        ),
    ]
