# Generated by Django 3.2.6 on 2021-09-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20210913_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='契約ID'),
        ),
    ]
