# Generated by Django 3.2.6 on 2021-09-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_contractmodel_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='sum',
        ),
    ]
