# Generated by Django 3.2.6 on 2021-09-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210910_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name_plural': '顧客データ'},
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
    ]
