# Generated by Django 3.2.6 on 2021-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_contractmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='billdate',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='差引残金入金日'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='chonai1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='町内会費(当月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='chonai2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='町内会費(翌月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='chukai',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='仲介手数料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='clean',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='清掃料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='cyrinder',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='シリンダー交換料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='deposit',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='合計金額(税込)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etc1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='その他1(備考欄参照)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etc2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='その他2(備考欄参照)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etc3',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='その他3(備考欄参照)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='ff',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='FF分解整備料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='gakusei',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='学生証写し'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='gokaku',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='合格通知書'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='hoken',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='社会保険証写し'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='hosyo',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='月額保証料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='hosyoitaku',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='初回保証委託料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='inkan',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='印鑑証明書'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='jumin1',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='入居者全員住民票(本籍省略)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='jumin2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='入居者全員住民票(本籍記載)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='kanrihi1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='管理費(当月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='kanrihi2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='管理費(翌月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='kasai',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='火災保険料'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='kyoekihi1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='共益費(当月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='kyoekihi2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='共益費(翌月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='mibun',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='身分証明書写し'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='month1',
            field=models.PositiveSmallIntegerField(blank=True, default='1', null=True, verbose_name='当月'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='month2',
            field=models.PositiveSmallIntegerField(blank=True, default='1', null=True, verbose_name='翌月'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='naitei',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='内定通知書'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='park1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='駐車場費(当月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='park2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='駐車場費(翌月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='reikin',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='礼金'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='shikikin',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='敷金'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='syaken',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='車検証写し'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='syotoku',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='所得証明書'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='合計金額(税込)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='yachin1',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='家賃(当月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='yachin2',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='家賃(翌月)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='zaiseki',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='在籍証明書'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='zankin',
            field=models.PositiveSmallIntegerField(blank=True, default='0', null=True, verbose_name='差引残金'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='nameen',
            field=models.CharField(default='', max_length=100, verbose_name='Lastname Firstname'),
        ),
    ]
