# Generated by Django 3.2.6 on 2021-09-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210915_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='done',
            field=models.BooleanField(default=False, verbose_name='処理済'),
        ),
    ]
