# Generated by Django 3.2.6 on 2021-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_remove_contractmodel_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='chonai1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='町内会費(当月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='chonai2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='町内会費(翌月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='chukai',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目3金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='cyrinder',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目7金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='deposit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='手付金'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='etc3',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目4金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='ff',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目6金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='hosyo',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目1金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='hosyoitaku',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目5金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item8bill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目8金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='itemb9ill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目9金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kanrihi1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='管理費(当月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kanrihi2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='管理費(翌月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kasai',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='項目2金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kyoekihi1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='共益費(当月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kyoekihi2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='共益費(翌月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='park1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='駐車場費(当月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='park2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='駐車場費(翌月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='reikin',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='礼金'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='shikikin',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='敷金'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='yachin1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='家賃(当月)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='yachin2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='家賃(翌月)'),
        ),
    ]
