# Generated by Django 3.2.6 on 2021-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20210915_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='done',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='etc2',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目1'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目2'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目3'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item4',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目4'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item5',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目5'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item6',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目6'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item7',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目7'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item8',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目8'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='itembill',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
    ]
