# Generated by Django 3.2.6 on 2021-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20210916_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='etc1',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='itembill',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item8bill',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目8金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='item9',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='項目9'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='itemb9ill',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目8金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='chukai',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目3金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='cyrinder',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目7金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='etc3',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目4金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='ff',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目6金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='hosyo',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目1金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='hosyoitaku',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目5金額'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item1',
            field=models.CharField(blank=True, default='月額保証料', max_length=50, null=True, verbose_name='項目1'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item2',
            field=models.CharField(blank=True, default='火災保険料', max_length=50, null=True, verbose_name='項目2'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item3',
            field=models.CharField(blank=True, default='仲介手数料', max_length=50, null=True, verbose_name='項目3'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item4',
            field=models.CharField(blank=True, default='清掃料', max_length=50, null=True, verbose_name='項目4'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item5',
            field=models.CharField(blank=True, default='初回保証委託料', max_length=50, null=True, verbose_name='項目5'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item6',
            field=models.CharField(blank=True, default='FF分解整備料', max_length=50, null=True, verbose_name='項目6'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='item7',
            field=models.CharField(blank=True, default='シリンダー交換料', max_length=50, null=True, verbose_name='項目7'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='kasai',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目2金額'),
        ),
    ]
