# Generated by Django 3.2.6 on 2021-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_customermodel_contractinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='tel',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='tel1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号1'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='tel2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号2'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='contractInfo',
            field=models.CharField(default='物件名等', max_length=20, verbose_name='契約情報'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX'),
        ),
    ]
