# Generated by Django 3.2.6 on 2021-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20210918_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='adbill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='広告料金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='ectitem1bill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='上記外項目1金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='ectitem2bill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='上記外項目2金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='ectitem3bill',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='上記外項目3金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etcitem1',
            field=models.CharField(blank=True, default='火災保険料', max_length=50, null=True, verbose_name='上記外項目1'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etcitem2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='上記外項目2'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='etcitem3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='上記外項目3'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='key1',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='鍵本数(部屋)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='reportdoc',
            field=models.TextField(blank=True, default='・入居申込書\n・契約書コピー（別紙特約、覚書等）\n・重説控え（原本）\n・保証会社申込書（身分証明書等含）\n・保証会社承認通知書\n・保証会社契約書控え（コピー）\n・鍵受領書\n・', null=True, verbose_name='契約関係書類報告書\u3000添付書類'),
        ),
    ]
