# Generated by Django 3.2.6 on 2021-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20210916_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='gakusei',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='gokaku',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='hoken',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='inkan',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='jumin1',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='jumin2',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='mibun',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='naitei',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='syaken',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='syotoku',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='zaiseki',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc1',
            field=models.CharField(blank=True, default='入居者全員住民票(本籍省略)', max_length=50, null=True, verbose_name='必要書類1'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc1a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc1b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc1c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc2',
            field=models.CharField(blank=True, default='入居者全員住民票(本籍記載)', max_length=50, null=True, verbose_name='必要書類1'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc2a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc2b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc2c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類1_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc3',
            field=models.CharField(blank=True, default='印鑑証明書', max_length=50, null=True, verbose_name='必要書類3'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc3a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類3_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc3b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類3_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc3c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類3_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc4',
            field=models.CharField(blank=True, default='身分証明書写し', max_length=50, null=True, verbose_name='必要書類4'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc4a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類4_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc4b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類4_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc4c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類4_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc5',
            field=models.CharField(blank=True, default='社会保険証写し', max_length=50, null=True, verbose_name='必要書類5'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc5a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類5_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc5b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類5_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc5c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類5_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc6',
            field=models.CharField(blank=True, default='所得証明書', max_length=50, null=True, verbose_name='必要書類6'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc6a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類6_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc6b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類6_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc6c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類6_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc7',
            field=models.CharField(blank=True, default='車検証写し', max_length=50, null=True, verbose_name='必要書類7'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc7a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類7_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc7b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類7_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc7c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類7_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc8',
            field=models.CharField(blank=True, default='学生証写し', max_length=50, null=True, verbose_name='必要書類8'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc8a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類8_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc8b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類8_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc8c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類8_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc9',
            field=models.CharField(blank=True, default='在籍証明書', max_length=50, null=True, verbose_name='必要書類9'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc9a',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類9_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc9b',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類9_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doc9c',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類9_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='doca',
            field=models.CharField(blank=True, default='内定通知書', max_length=50, null=True, verbose_name='必要書類10'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docaa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類10_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docab',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類10_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docac',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類10_連帯保証人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docb',
            field=models.CharField(blank=True, default='合格通知書', max_length=50, null=True, verbose_name='必要書類11'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docba',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類11_契約者'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docbb',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類11_同居人'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='docbc',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='必要書類11_連帯保証人'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='itemb9ill',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='項目9金額'),
        ),
    ]
