# Generated by Django 3.2.6 on 2021-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20210919_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractmodel',
            old_name='ectitem1bill',
            new_name='etcitem1bill',
        ),
        migrations.RenameField(
            model_name='contractmodel',
            old_name='ectitem2bill',
            new_name='etcitem2bill',
        ),
        migrations.RenameField(
            model_name='contractmodel',
            old_name='ectitem3bill',
            new_name='etcitem3bill',
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='etcitem1',
            field=models.CharField(blank=True, default='火災保険料(2年)', max_length=50, null=True, verbose_name='上記外項目1'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='etcitem2',
            field=models.CharField(blank=True, default='ハウスクリーニング料(退去時)', max_length=50, null=True, verbose_name='上記外項目2'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='etcitem3',
            field=models.CharField(blank=True, default='シリンダー交換料(退去時)', max_length=50, null=True, verbose_name='上記外項目3'),
        ),
    ]
