# Generated by Django 3.2.6 on 2021-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20210916_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='特記事項'),
        ),
    ]
