# Generated by Django 3.2.6 on 2021-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20210910_0529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name_plural': '顧客管理データ'},
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='contractCategory',
            field=models.CharField(blank=True, choices=[('Rent', '賃貸'), ('Buy', '購入'), ('Sell', '売却'), ('Other', 'その他')], max_length=10, null=True, verbose_name='契約種別'),
        ),
    ]
