# Generated by Django 3.2.6 on 2021-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20210910_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='firstnamekana',
            field=models.CharField(default='', max_length=20, verbose_name='名（フリガナ）'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='lastnamekana',
            field=models.CharField(default='', max_length=20, verbose_name='姓（フリガナ）'),
        ),
    ]
