# Generated by Django 3.2.6 on 2021-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20210920_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractmodel',
            old_name='receiptremarks2',
            new_name='azukari_remarks2',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='azukari_atena',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='預り証\u3000宛名'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='azukari_meimo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='預り証\u3000但し書き'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='azukari_total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='預り証\u3000合計金額'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='receipt_atena',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='領収書\u3000宛名'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='receipt_meimo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='領収書\u3000但し書き'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='receipt_total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='領収書\u3000合計金額'),
        ),
    ]
