# Generated by Django 3.2.6 on 2021-09-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_contractmodel_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='nameen',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='jusetsudate',
            field=models.DateField(blank=True, default=None, verbose_name='重説実施日'),
        ),
    ]
