# Generated by Django 3.2.6 on 2021-09-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20210911_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='店舗名')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='FAX')),
                ('bank', models.CharField(blank=True, max_length=20, null=True, verbose_name='銀行名')),
                ('bankbranch', models.CharField(blank=True, max_length=20, null=True, verbose_name='支店名')),
                ('bankaccount', models.CharField(blank=True, max_length=20, null=True, verbose_name='口座')),
                ('bankid', models.CharField(blank=True, max_length=100, null=True, verbose_name='名義')),
                ('bankkana', models.CharField(blank=True, max_length=100, null=True, verbose_name='フリガナ')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '店舗データ',
            },
        ),
    ]
