# Generated by Django 3.2.6 on 2021-09-23 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20210922_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='gas',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ガス会社'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='submitdoc',
            field=models.TextField(blank=True, default='・建物賃貸借契約書（2部）\n・使用規則（2部）\n・原状回復の条件について（2部）\n・鍵預り証（1部）\n・リペアサービス申込書（1部）\n・保証会社申込書類（1式）\n・重要事項説明書写し（仲介業者書式）\n\n・火災保険加入書類\n・御入居者様へのご案内\n・物件状況チェックリスト', null=True, verbose_name='契約費明細\u3000提出書類'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month1',
            field=models.IntegerField(blank=True, default=9, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='当月'),
        ),
    ]
