# Generated by Django 3.2.6 on 2021-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_alter_contractmodel_jusetsudate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='contractdate',
            field=models.DateField(auto_now=True, null=True, verbose_name='契約開始日'),
        ),
    ]
