# Generated by Django 3.2.6 on 2021-09-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_corpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpmodel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='店舗名'),
        ),
    ]
