# Generated by Django 3.2.6 on 2021-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_auto_20210924_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='azukari_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='預り書\u3000発行日'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='receipt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='領収書\u3000発行日'),
        ),
    ]
