# Generated by Django 3.2.6 on 2021-09-30 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0013_auto_20210928_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='staff',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='responsiblestaff',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='責任担当者'),
        ),
    ]
