# Generated by Django 3.2.6 on 2021-09-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_alter_contractmodel_contractdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='jusetsudate',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='jsdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='重説実施日'),
        ),
    ]
