# Generated by Django 3.2.6 on 2021-09-30 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20210930_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='month1',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='当月'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month2',
            field=models.PositiveSmallIntegerField(blank=True, default=11, null=True, verbose_name='翌月'),
        ),
    ]
