# Generated by Django 3.2.6 on 2021-10-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_auto_20211001_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='kanridoc',
            field=models.TextField(blank=True, default='拝啓\u3000時下益々ご清栄のこととお慶び申し上げます。\n\n', null=True, verbose_name='管理会社宛FAX\u3000本文'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='transremarks',
            field=models.TextField(blank=True, default='拝啓\u3000時下ますますご清栄のこととお慶び申し上げます。', null=True, verbose_name='引越見積依頼書\u3000備考'),
        ),
    ]
