# Generated by Django 3.2.6 on 2021-10-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_auto_20211003_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractmodel',
            old_name='adbill',
            new_name='adfee',
        ),
        migrations.RenameField(
            model_name='contractmodel',
            old_name='chukai',
            new_name='brokerage',
        ),
    ]
