# Generated by Django 3.2.6 on 2021-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0017_auto_20211004_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='key1name',
            field=models.CharField(blank=True, default='部屋', max_length=50, null=True, verbose_name='鍵A(番号)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='key2name',
            field=models.CharField(blank=True, default='車庫', max_length=50, null=True, verbose_name='鍵B(番号)'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='key3name',
            field=models.CharField(blank=True, default='トランクルーム', max_length=50, null=True, verbose_name='鍵C(番号)'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='key1',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='鍵A本数'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='key2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='鍵B本数'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='key3',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='鍵C本数'),
        ),
    ]
