# Generated by Django 3.2.6 on 2021-10-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_auto_20211007_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='kanristaff',
            field=models.CharField(blank=True, default='ご担当者様', max_length=50, null=True, verbose_name='管理会社担当者名'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='transstaff',
            field=models.CharField(blank=True, default='ご担当者様', max_length=50, null=True, verbose_name='引越業者担当者名'),
        ),
    ]
