# Generated by Django 3.2.6 on 2021-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0019_auto_20211008_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='kanristaff',
            field=models.CharField(blank=True, default='ご担当者', max_length=50, null=True, verbose_name='管理会社担当者名'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='transstaff',
            field=models.CharField(blank=True, default='ご担当者', max_length=50, null=True, verbose_name='引越業者担当者名'),
        ),
    ]
