# Generated by Django 3.2.6 on 2021-10-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_auto_20211009_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffModel',
        ),
    ]
