# Generated by Django 3.2.6 on 2021-10-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0021_delete_staffmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='total',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='zankin',
        ),
    ]
