# Generated by Django 3.2.6 on 2021-10-29 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0022_auto_20211021_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='非表示')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='件名')),
                ('limitdate', models.DateField(auto_now_add=True, verbose_name='支払期限')),
                ('postdate', models.DateField(auto_now_add=True, null=True, verbose_name='登録日時')),
                ('update', models.DateField(auto_now=True, null=True, verbose_name='更新日時')),
                ('i1name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i1more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i1price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i1num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i2name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i2more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i2price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i2num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i3name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i3more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i3price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i3num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i4name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i4more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i4price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i4num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i5name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i5more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i5price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i5num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i6name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i6more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i6price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i6num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i7name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i7more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i7price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i7num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i8name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i8more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i8price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i8num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('i9name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('i9more', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('i9price', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('i9num', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('ianame', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('iamore', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('iaprice', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('ianum', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('ibname', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('ibmore', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('ibprice', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('ibnum', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('icname', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目')),
                ('icmore', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細')),
                ('icprice', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='単価')),
                ('icnum', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='数量')),
                ('remarks', models.TextField(blank=True, default='', null=True, verbose_name='預り証\u3000備考')),
                ('corp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.corpmodel', verbose_name='担当店舗')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.customermodel', verbose_name='氏名')),
                ('responsiblestaff', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='責任担当者')),
            ],
            options={
                'verbose_name_plural': '11_請求書データ',
            },
        ),
    ]
