# Generated by Django 3.2.6 on 2021-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0023_invoicemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={'verbose_name_plural': '61_請求書データ'},
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='請求書発行日'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='宛名'),
        ),
    ]
