# Generated by Django 3.2.6 on 2021-10-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0024_auto_20211030_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9more',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9num',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9price',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iamore',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ianame',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ianum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iaprice',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibmore',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibnum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibprice',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icmore',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='詳細L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icnum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='数量L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icprice',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='単価L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='請求書\u3000備考'),
        ),
    ]
