# Generated by Django 3.2.6 on 2021-11-06 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0025_auto_20211030_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='completed',
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='idmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='idname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='idnum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='idprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iemore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iename',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ienum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ieprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ifmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ifname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ifnum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ifprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='igmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='igname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ignum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='igprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ihmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ihname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ihnum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ihprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iimore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iiname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iinum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iiprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ijmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ijname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ijnum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ijprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ikmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ikname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='品目'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='iknum',
            field=models.FloatField(default=0, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ikprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month1',
            field=models.IntegerField(blank=True, default=11, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='当月'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='month2',
            field=models.PositiveSmallIntegerField(blank=True, default=12, null=True, verbose_name='翌月'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1num',
            field=models.FloatField(default=0, verbose_name='数量A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1price',
            field=models.SmallIntegerField(default=0, verbose_name='単価A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2num',
            field=models.FloatField(default=0, verbose_name='数量B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2price',
            field=models.SmallIntegerField(default=0, verbose_name='単価B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3num',
            field=models.FloatField(default=0, verbose_name='数量C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3price',
            field=models.SmallIntegerField(default=0, verbose_name='単価C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4num',
            field=models.FloatField(default=0, verbose_name='数量D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4price',
            field=models.SmallIntegerField(default=0, verbose_name='単価D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5num',
            field=models.FloatField(default=0, verbose_name='数量E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5price',
            field=models.SmallIntegerField(default=0, verbose_name='単価E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6num',
            field=models.FloatField(default=0, verbose_name='数量F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6price',
            field=models.SmallIntegerField(default=0, verbose_name='単価F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7num',
            field=models.FloatField(default=0, verbose_name='数量G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7price',
            field=models.SmallIntegerField(default=0, verbose_name='単価G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8num',
            field=models.FloatField(default=0, verbose_name='数量H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8price',
            field=models.SmallIntegerField(default=0, verbose_name='単価H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9more',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9num',
            field=models.FloatField(default=0, verbose_name='数量I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9price',
            field=models.SmallIntegerField(default=0, verbose_name='単価I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iamore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ianum',
            field=models.FloatField(default=0, verbose_name='数量J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iaprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibnum',
            field=models.FloatField(default=0, verbose_name='数量K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icmore',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='詳細L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icnum',
            field=models.FloatField(default=0, verbose_name='数量L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icprice',
            field=models.SmallIntegerField(default=0, verbose_name='単価L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='responsiblestaff',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
    ]
