# Generated by Django 3.2.6 on 2021-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0026_auto_20211107_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='i1more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細A'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i2more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細B'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i3more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細C'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i4more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細D'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i5more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細E'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i6more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細F'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i7more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細G'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i8more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細H'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='i9more',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細I'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iamore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細J'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ibmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細K'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='icmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細L'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='idmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iemore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ifmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='igmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ihmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='iimore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ijmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='ikmore',
            field=models.CharField(blank=True, default='_', max_length=50, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='limitdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='支払期限'),
        ),
    ]
