# Generated by Django 3.2.6 on 2021-09-23 20:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0012_auto_20210924_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage', models.IntegerField(blank=True, default=0, null=True, verbose_name='仲介手数料')),
                ('adfee', models.IntegerField(blank=True, default=0, null=True, verbose_name='広告料')),
                ('hangingfee', models.IntegerField(blank=True, default=0, null=True, verbose_name='事務手数料')),
                ('etc1fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='その他手数料')),
                ('etc2fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='予備枠')),
                ('zankin', models.IntegerField(blank=True, default=0, null=True, verbose_name='残金')),
                ('receive', models.BooleanField(default=False, verbose_name='回収フラグ')),
                ('receivemonth', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='回収月')),
                ('receivedate', models.DateField(blank=True, default=None, null=True, verbose_name='回収日')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.contractmodel', verbose_name='契約データ')),
                ('responsiblestaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '11_売上管理',
            },
        ),
    ]
