# Generated by Django 3.2.6 on 2021-09-24 20:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='postdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='update',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='etc1fee',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='receivemonth',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='回収月'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='responsiblestaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='担当者名'),
        ),
    ]
