# Generated by Django 3.2.6 on 2021-09-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210925_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmodel',
            old_name='postdate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='salesmodel',
            old_name='update',
            new_name='updated_at',
        ),
    ]
