# Generated by Django 3.2.6 on 2021-09-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210925_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='salesmodel',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
