# Generated by Django 3.2.6 on 2021-09-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20210925_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesmodel',
            name='updated_at',
        ),
    ]
