# Generated by Django 3.2.6 on 2021-10-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0015_auto_20211001_0631'),
        ('sales', '0005_auto_20210928_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.contractmodel', verbose_name='契約データ'),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='responsiblestaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当者名'),
        ),
    ]
