# Generated by Django 3.2.6 on 2021-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20211002_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='corp',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='支店'),
        ),
    ]
